### ISSUE TITLE
친구요청을 받을 시 이름이 두번 뜹니다.

### ISSUE THREAD

**Issue by minty99** [swsnu/swpp18-team9#27]
<img width="217" alt="screenshot at dec 12 19-44-38" src="https://user-images.githubusercontent.com/3724119/49864709-6f1ae700-fe46-11e8-8047-a78c1ba06ff7.png">
이렇게 두번 뜹니다. 항상 그런지는 잘 모르겠습니다.

**Comment by tldn0718** [comment]
혹시 이름과 성에 각각 "김태희"를 입력하셨나요? 이름과 성을 합쳐서 표시되게 해놔서 그런거일까봐 여쭤봅니다
